---
# Install consul and base config
- name: Install consul
  ansible.builtin.include_role:
    name: install-hashi
  vars:
    name: consul

- name: Install consul-template
  ansible.builtin.package:
    name: consul-template
    state: present

- name: Ensure consul bootstrap is ok
  ansible.builtin.include_role:
    name: bootstrap-consul
  #when: consul_bootstrap_token is not defined
  when: consul_gossip_key is not defined

# is this needed?
#- ansible.builtin.include_tasks: ./update-config.yml

- name: Check that the CA for consul exists
  ansible.builtin.stat:
    path: "{{ configdir }}/consul.d/consul-agent-ca.pem"
  register: stat_result

- name: Consul TLS client
  ansible.builtin.shell: consul tls ca create && consul tls cert create -server -dc {{ datacenter }} && consul tls cert create -client -dc {{ datacenter }}
  args:
    chdir: "{{ configdir }}/consul.d"
  when: not stat_result.stat.exists

- name: Ensure consul.d directory ownership
  ansible.builtin.file:
    path: "{{ configdir }}/consul.d"
    state: directory
    owner: hashi
    group: hashi
    recurse: true

# - name: Write Roles and policies
#   ansible.builtin.include_role:
#     name: consul-acl

- ansible.builtin.include_tasks: ./update-config.yml

- name: Configure dnsmasq forwarding
  ansible.builtin.copy:
    content: |
      server=/consul/127.0.0.1#8600
      server=/shamsway.net/127.0.0.1#8600
    dest: /etc/dnsmasq.d/shamsway.conf
    owner: root
    group: root
    mode: "0644"
