---
- name: Add new folders to Nomad configuration
  gather_facts: no
  hosts: localhost

  tasks:
    - name: Read volumes from CSV file
      ansible.builtin.read_csv:
        path: volumes.csv
        delimiter: ','
      register: volumes_csv

    - name: Set volume facts
      ansible.builtin.set_fact:
        volumes: "{{ volumes_csv.list }}"

    - name: Check if volume is already defined
      ansible.builtin.lineinfile:
        path: inventory/groups.yml
        regexp: '^        - name: {{ item.name }}'
        line: ''
        state: absent
      check_mode: yes
      register: volume_exists
      loop: "{{ volumes }}"

    - name: Add new volumes to inventory variables
      ansible.builtin.blockinfile:
        path: inventory/groups.yml
        append_newline: false
        prepend_newline: false
        block: |
              {% for item in volumes_csv.list %}
              {% if not volume_exists.results[loop.index0].found %}
              {% filter indent(width=6, first=true) %}
              - name: {{ item.name }}
                path: {{ item.path }}
                backup: {{ item.backup }}
              {% endfilter %}
              {% endif %}
              {% endfor %}
        insertafter: '^      volumes:'
      loop: "{{ volumes }}"
      when: volume_exists.results | selectattr('found', 'equalto', false) | list | length > 0

#     - name: Run configure-mounts.yml playbook
#       ansible.builtin.import_playbook: configure-mounts.yml

# - name: Update Nomad configuration on home lab servers
#   hosts: servers
#   serial: 1

#   tasks:
#     - name: Run configure-mounts.yml playbook
#       ansible.builtin.import_playbook: update-nomad.yml