---
- name: Manage mountpoints across home lab
  hosts: servers
  user: root
  become: true
  gather_facts: true

  vars:
    nfs_shares:
      - server: 192.168.252.9
        export_path: /nfs/services
        mount_path: /mnt/services
    smb_shares:
      - server: 192.168.252.5
        share_name: Recordings
        mount_path: /mnt/recordings
        username: smbuser
        password: uGgKWn-dz6rZP.vc

  tasks:
    - name: Install NFS and SMB packages
      ansible.builtin.package:
        name:
          - nfs-common
          - nfs4-acl-tools
          - cifs-utils
          - smbclient
        state: present

    - name: Ensure NFS and SMB mount directories exist
      ansible.builtin.file:
        path: "{{ item.mount_path }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0755"
      loop: "{{ nfs_shares + smb_shares }}"

    - name: Mount NFS shares
      ansible.posix.mount:
        src: "{{ item.server }}:{{ item.export_path }}"
        path: "{{ item.mount_path }}"
        fstype: nfs
        opts: defaults
        state: mounted
      loop: "{{ nfs_shares }}"

    - name: Mount SMB shares
      ansible.posix.mount:
        src: //{{ item.server }}/{{ item.share_name }}
        path: "{{ item.mount_path }}"
        fstype: cifs
        opts: username={{ item.username }},password={{ item.password }},cache=strict,uid=2000,gid=100,file_mode=0644,dir_mode=0755,vers=3.0
        state: mounted
      loop: "{{ smb_shares }}"

    - name: Update /etc/fstab with NFS and SMB entries
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{ item.server }}:{{ item.export_path }} {{ item.mount_path }} nfs defaults 0 0"
        state: present
      loop: "{{ nfs_shares }}"

    - name: Update /etc/fstab with SMB entries
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "//{{ item.server }}/{{ item.share_name }} {{ item.mount_path }} cifs username={{ item.username }},password={{ item.password }},cache=strict,uid=2000,gid=100,file_mode=0644,dir_mode=0755,vers=3.0 0 0"
        state: present
      loop: "{{ smb_shares }}"

    - name: Set ownership of mounted directories
      ansible.builtin.file:
        path: "{{ item.mount_path }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        recurse: true
      loop: "{{ nfs_shares + smb_shares }}"

    - name: Ensure inventory-defined folders exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0755"
      loop: "{{ volumes }}"
