---
- name: Apply updates to Consul Servers
  hosts: servers
  user: root
  become: true
  gather_facts: true
  serial: 1
  max_fail_percentage: 0
  tasks:
    - name: Update consul-server config
      ansible.builtin.template:
        src: roles/consul-server/templates/nomad-agent.hcl.j2
        dest: "{{ configdirs['consul-server'] }}/consul-server.hcl"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0644"
      vars:
        role_name: consul-server

    - name: Restart consul-server services
      become: true
      become_user: root
      block:
        - name: Restart consul-server service
          ansible.builtin.service:
            name: consul-server
            state: restarted
          changed_when: false

        - name: Wait for {{ inventory_hostname }} consul-server to start
          ansible.builtin.wait_for:
            port: "{{ consul.ports.http }}"
            timeout: 60
          changed_when: false
