---
- name: Apply updates to {{ service_name }}
  hosts: servers
  user: root
  become: true
  gather_facts: true
  serial: 1
  max_fail_percentage: 0
  tasks:
    - name: Update {{ service_name }} config
      ansible.builtin.template:
        src: roles/{{ service_name }}/templates/{{ service_name }}.hcl.j2
        dest: "{{ configdirs[~ service_name] }}/{{ service_name }}.hcl"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0644"
      vars:
        role_name: consul-server

    - name: Restart consul-server services
      become: true
      become_user: root
      block:
        - name: Restart consul-server service
          ansible.builtin.service:
            name: consul-server
            state: restarted
          changed_when: false

        - name: Wait for {{ inventory_hostname }} consul-server to start
          ansible.builtin.wait_for:
            port: "{{ consul.ports.http }}"
            timeout: 60
          changed_when: false
