---
- name: Apply updates to Nomad Servers and Agents
  hosts: servers
  user: "{{ admin_user }}"
  become: true
  gather_facts: true
  serial: 1
  max_fail_percentage: 0
  vars_files:
    - .secrets.yml
  tasks:
    - name: Update nomad-server configs
      ansible.builtin.include_tasks: 
        file: update-nomad.yml
      vars:
        port: "{{ nomad.ports.http }}"
        service_name: "nomad-server"

    - name: Update nomad-agent configs
      ansible.builtin.include_tasks: 
        file: update-nomad.yml
      vars:
        port: "{{ nomad.ports.agent_http }}"
        service_name: "nomad-agent"

    - name: Update nomad-agent-root configs
      ansible.builtin.include_tasks: 
        file: update-nomad.yml
      vars:
        port: "{{ nomad.ports.root_agent_http }}"
        service_name: "nomad-agent-root"        