---
- name: Apply updates to Nomad
  hosts: servers
  user: root
  become: true
  gather_facts: true
  serial: 1
  max_fail_percentage: 0
  tasks:
    - name: Update Podman user config
      become: true
      become_user: "{{ user }}"
      ansible.builtin.copy:
        src: roles/nomad/files/containers.conf
        dest: ~/.config/containers
        mode: "0644"

    - name: Update system container registries
      become: true
      become_user: "root"
      ansible.builtin.copy:
        src: roles/nomad/files/registries.conf
        dest: /etc/containers/registries.conf
        mode: "0644"

    - name: Update Nomad config
      ansible.builtin.template:
        src: roles/nomad/templates/nomad.hcl.j2
        dest: "{{ configdir }}/nomad.d/nomad.hcl"
        owner: hashi
        group: hashi
        mode: "0644"

    - name: Restart Nomad service
      become: true
      become_user: root
      block:
        - name: Drain Nomad node
          ansible.builtin.command: nomad node drain -self -enable -force -m "nomad config update" -yes
          changed_when: false
          register: drain_output

        - name: Verify Nomad node is drained
          ansible.builtin.command: nomad node status -self
          changed_when: false
          register: node_status
          until: "'Node drain complete' in node_status.stdout"
          retries: 6
          delay: 5

        - name: Restart Podman service
          become: true
          become_user: "{{ user }}"
          ansible.builtin.systemd_service:
            name: podman.service
            state: restarted
            scope: user
          changed_when: false

        - name: Restart Podman socket
          become: true
          become_user: "{{ user }}"
          ansible.builtin.systemd_service:
            name: podman.socket
            state: restarted
            scope: user
          changed_when: false

        - name: Restart Nomad service
          ansible.builtin.service:
            name: nomad
            state: restarted
          changed_when: false

        - name: Wait for Nomad to start
          ansible.builtin.wait_for:
            port: 4646
            timeout: 60
          changed_when: false

        - name: Verify Nomad is running
          ansible.builtin.command: nomad status
          register: nomad_status
          changed_when: false

        - name: Disable Nomad node drain
          ansible.builtin.command: nomad node drain -self -disable
          changed_when: false
          register: disable_drain_output

        - name: Verify Nomad node drain is disabled
          ansible.builtin.command: nomad node status -self
          changed_when: false
          register: node_status_after
          until: "'ineligible' not in node_status_after.stdout"
          retries: 6
          delay: 5
