---
- name: Ensure nomad-server is in a running state
  service:
    name: nomad-server
    state: started
  register: consulServiceDetails
  until: consulServiceDetails.status.ActiveState == "active"
  retries: 5
  delay: 10

- name: Generate Nomad gossip key
  ansible.builtin.command: openssl rand -base64 32
  register: nomad_gossip_key_output

- name: Set Nomad gossip key fact
  ansible.builtin.set_fact:
    consul_gossip_key: "{{ nomad_gossip_key_output.stdout }}"

- name: Save Nomad values to .secrets.yml
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/.secrets.yml"
    regexp: '^{{ item.name }}:'
    line: "{{ item.name }}: {{ item.value }}"
    create: true
  delegate_to: localhost
  become: false
  loop:
    - { name: nomad_gossip_key, value: "{{ nomad_gossip_key }}" }
