---
- name: Ensure nomad-server is in a running state
  service:
    name: nomad-server
    state: started
  register: nomadServiceDetails
  until: nomadServiceDetails.status.ActiveState == "active"
  retries: 5
  delay: 10

- name: Generate Nomad gossip key
  ansible.builtin.command: openssl rand -base64 32
  register: nomad_gossip_key_output

- name: Set Nomad gossip key fact
  ansible.builtin.set_fact:
    nomad_gossip_key: "{{ nomad_gossip_key_output.stdout }}"

- name: Save Nomad values to .secrets.yml
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/.secrets.yml"
    regexp: '^{{ item.name }}:'
    line: "{{ item.name }}: {{ item.value }}"
    create: true
  delegate_to: localhost
  become: false
  loop:
    - { name: nomad_gossip_key, value: "{{ nomad_gossip_key }}" }

- name: Writing shell profile for ssh user on {{ inventory_hostname.split('.')[0] }}
  become: false
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    regexp: ^export {{ item.key }}
    line: export {{ item.key }}={{ item.value }}
    create: true
  with_dict:
    NOMAD_ADDR: "https://nomad.{{ datacenter }}.{{ tld }}:{{ nomad.ports.https }}"
    NOMAD_CACERT: "{{ configdirs['tls'] }}/consul-agent-ca.pem"
    NOMAD_CLIENT_CERT: "{{ configdirs['tls'] }}/{{ datacenter }}-cli-consul-0.pem"
    NOMAD_CLIENT_KEY: "{{ configdirs['tls'] }}/{{ datacenter }}-cli-consul-0-key.pem" 

- name: Adding environment variables to direnv
  ansible.builtin.lineinfile:
    dest: ./.envrc
    regexp: ^export {{ item.key }}
    line: export {{ item.key }}={{ item.value }}
    create: true
  delegate_to: localhost
  become: false
  with_dict:
    NOMAD_ADDR: "https://nomad.{{ datacenter }}.{{ tld }}:{{ nomad.ports.https }}"
    NOMAD_CACERT: "~/.tls/consul-agent-ca.pem"
    NOMAD_CLIENT_CERT: "~/.tls/{{ datacenter }}-cli-consul-0.pem"
    NOMAD_CLIENT_KEY: "~/.tls/{{ datacenter }}-cli-consul-0-key.pem" 
