apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.service.consul:9091
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki.service.consul:3100
    editable: true

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo.service.consul:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags:
          - key: job
          - key: instance
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: job
          - key: instance
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
