---
- name: Check if {{ key_name }} is defined
  ansible.builtin.set_fact:
    key_defined: "{{ lookup('vars', key_name) | default('', true) }}"

- ansible.builtin.debug:
    msg:
      - "{{ key_name }} from hostvars: {{ lookup('vars', key_name) | default('', true) }}"
      - "key_defined: {{ key_defined }}"

- name: Generating key for {{ key_name }}
  ansible.builtin.include_tasks: ./write-key.yml
  when: not key_defined
