---
# Debug message to indicate the start of the write-key task
- name: Debug write-key
  ansible.builtin.debug:
    msg:
      - write-key started
      - "key_name: {{ key_name }}"
      - "cmd: {{ cmd }}"

# Generate the key using the provided command
- name: Generate key {{ key_name }} with cmd
  ansible.builtin.shell: "{{ cmd }}"
  register: key_cmd

# Debug message to display the generated key
- name: Debug key_cmd.stdout
  ansible.builtin.debug:
    msg:
      - "key_cmd: {{ key_cmd }}"
      - "key_cmd.stdout: {{ key_cmd.stdout }}"

# Set a fact with the generated key
- name: Set fact {{ key_name }}
  ansible.builtin.set_fact:
    "{{ key_name }}": "{{ key_cmd.stdout }}"
    cacheable: true
  no_log: false

# Save the generated key to host_vars
- name: Save to host_vars
  ansible.builtin.set_fact:
    "{{ key_name }}": "{{ key_cmd.stdout }}"
    cacheable: true
  delegate_to: localhost
  become: false

# Save the generated key to the secrets file
- name: Save to secrets
  ansible.builtin.lineinfile:
    dest: "{{ playbook_dir }}/.secrets.yml"
    line: "{{ key_name }}: {{ key_cmd.stdout }}"
    regexp: "^{{ key_name }}: {{ key_cmd.stdout | regex_escape }}$"
    create: true
    state: present
  delegate_to: localhost
  become: false
  when: write | default(true)
