---
- name: Install Consul Agent (root)
  ansible.builtin.include_role:
    name: install-hashi
  vars:
    name: consul-agent-root
    package: consul
    user: root
    group: root    

- name: Ensure consul.d directory ownership
  ansible.builtin.file:
    path: "{{ configdirs[role_name] }}"
    state: directory
    owner: root
    group: root
    recurse: true

- name: Create {{ role_name }} config
  ansible.builtin.template:
    src: "{{ role_name }}.hcl.j2"
    dest: "{{ configdirs[role_name] }}/{{ role_name }}.hcl"
    owner: root
    group: root
    mode: "0644"

- name: Restart consul
  ansible.builtin.systemd:
    name: "{{ role_name }}"
    state: restarted

