---
- name: Check if {{ user }} home folder exists
  ansible.builtin.file:
    path: "{{ datadir }}/home"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Ensure {{ user }} is a member of systemd-journal group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: systemd-journal
    append: true

- name: Create user systemd configuration directory
  ansible.builtin.file:
    path: "{{ datadir }}/home/.config/systemd/user/"
    state: directory
    mode: "0700"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Verify folder presence and ownership
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"
  loop: "{{ volumes }}"
  
- name: Install {{ role_name }}
  ansible.builtin.include_role:
    name: install-hashi
  vars:
    name: consul-agent
    package: consul

- name: Ensure consul.d directory ownership
  ansible.builtin.file:
    path: "{{ configdirs[role_name] }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true

# Are tailscale IP plays still necessary?

- name: Get Tailscale IP
  when: tailscale_ip is not defined
  block:
  - name: Get Tailscale IP address
    ansible.builtin.command:
      cmd: tailscale ip -4
    register: tailscale_ip_output
    changed_when: false
    
  - name: Set Tailscale IP address as a variable
    ansible.builtin.set_fact:
      tailscale_ip: "{{ tailscale_ip_output.stdout }}"

- name: Create {{ role_name }} config
  ansible.builtin.template:
    src: "{{ role_name }}.hcl.j2"
    dest: "{{ configdirs[role_name]}}/{{ role_name }}.hcl"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: Restart {{ role_name }}
  ansible.builtin.systemd:
    name:  "{{ role_name }}"
    state: restarted

