---
- name: Install {{ role_name }}
  ansible.builtin.include_role:
    name: install-hashi
  vars:
    name: nomad-agent
    package: nomad

- name: Ensure {{ role-name }}.d directory ownership
  ansible.builtin.file:
    path: "{{ configdirs[role_name] }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true

- name: Include podman-rootless role
  include_role:
    name: podman-rootless

- name: Create {{ role_name }} config
  ansible.builtin.template:
    src: "{{ role_name }}.hcl.j2"
    dest: "{{ configdirs[role_name] }}/{{ role_name }}.hcl"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: Restart {{ role_name }}
  ansible.builtin.systemd:
    name:  "{{ role_name }}"
    state: restarted