---
serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https    
  websecure:
    address: ':443'
  traefik:
    address: ':8080'
  metrics:
    address: ":8082"    

api:
  dashboard: true
  insecure: true
  debug: true

ping: {}
accessLog: {}  

log:
 level: DEBUG

accessLog:
  format: json

certificatesResolvers:
  myresolver:
    acme:
      email: 'mattadamelliott@gmail.com'
      storage: '/etc/traefik/acme.json'
      keyType: 'RSA4096'
      dnschallenge:
        provider: 'cloudflare'
        delayBeforeCheck: 90
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'
        disablePropagationCheck: true

providers:
  providersThrottleDuration: 15s
  consulCatalog:
    cache: true
    prefix: 'traefik'
    exposedByDefault: false
    requireConsistent: true
    endpoint:
      address: 'consul.service.consul:8500'
      scheme: 'http'
      datacenter: 'shamsway'

metrics:
  prometheus:
    entryPoint: metrics

# metrics:
#   influxdb:
#     address: 'localhost:8086'
#     protocol: 'http'
#     pushinterval: '60s'
#     database: 'traefik'
#     retentionpolicy: 'traefik'