[global]
  checkNewVersion = false
  sendAnonymousUsage = false
[metrics]
  [metrics.prometheus]
    entrypoint = "metrics"
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.http]
    address = ":8080"
  [entryPoints.traefik]
    address = ":9002"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.metrics]
    address = ":8082"
[accessLog]
  format = "json"
  filePath = "/traefik-data/traefik-access.log"
[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"
[certificatesResolvers.cloudflare.acme]
  email = "${admin_email}"
  storage = "/acme/acme.json"
  [certificatesResolvers.cloudflare.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 30
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
[log]
  level = "INFO"
  #level = "DEBUG"
  filePath = "/traefik-data/traefik.log"
[api]
  dashboard = true
  insecure = true
[ping]
[providers.consulcatalog]
  exposedByDefault = false
  prefix = "traefik"
  defaultRule = "Host(`{{ .Name }}.${domain}`) || Host(`{{ .Name }}.service.consul`)"
  connectAware = false
  connectByDefault = false
  [providers.consulcatalog.endpoint]
    address = "${consul}:8501"
    scheme = "https"
    datacenter = "${datacenter}"
    endpointWaitTime = "15s"
    [providers.consulcatalog.endpoint.tls]
      insecureSkipVerify = true
      ca = "/tls/consul-agent-ca.pem"
      cert = "/tls/${datacenter}-client-consul-0.pem"
      key  = "/tls/${datacenter}-client-consul-0-key.pem"
