- name: Write-tokens.yml debug
  debug:
    msg: 
      - "ACL: {{ acl }}"
      - "Key name: consul_{{ acl_name }}_token"
      - "cmd: consul acl token create -description '{{ acl.descr }}' -token='{{ consul_bootstrap_token }}' -policy-name {{ (acl.policies | default(acl_name)) }} -format=json | jq -r '.SecretID'"

- name: Read or create keys (er, read-or-get-key?)
  include_role:
    name: read-or-get-key
  vars:
    key_name: "consul_{{ acl_name }}_token"
    cmd: "consul acl token create -description '{{ acl.descr }}' -token='{{ consul_bootstrap_token }}' -policy-name {{ (acl.policies | default(acl_name)) }} -format=json | jq -r '.SecretID'"