---
- name: Ensure gnupg and curl are installed
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: APT update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Restart Docker service
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Create docker.hcl configuration file
  ansible.builtin.copy:
    content: |
      plugin "docker" {
        config {
          endpoint = "unix:///var/run/docker.sock"        
          allow_privileged = true
          gc {
            image = true
            image_delay = "3m"
            container = true
            dangling_containers {
              enabled = true
              dry_run = false
              period = "5m"
              creation_grace = "5m"
            }
          }
          volumes {
            enabled = true
            selinuxlabel = "z"
          }
        }
      }
    dest: /opt/homelab/config/nomad.d/docker.hcl
    owner: hashi
    group: hashi
    mode: '0644'

- name: Restart Nomad service
  ansible.builtin.service:
    name: nomad
    state: restarted

- name: Wait for Nomad to start
  ansible.builtin.wait_for:
    port: 4646
    timeout: 60

- name: Verify Nomad is running
  ansible.builtin.command: nomad status
  register: nomad_status
  changed_when: false