---
# Secrets role defaults
secrets_provider: "{{ lookup('env', 'SECRETS_PROVIDER') | default('env_file', true) }}"
secrets_env_file: "{{ datadir }}/.env"
secrets_env_template: "{{ playbook_dir }}/.env.template"
op_vault_name: "Octant"
