---
- name: Install {{ role_name }}
  ansible.builtin.include_role:
    name: install-hashi
  vars:
    name: nomad-server
    package: consul
    user: root
    group: root

- name: Check for nomad_gossip_key and generate if needed
  ansible.builtin.include_role:
    name: configure-nomad
  when: nomad_gossip_key is not defined

- name: Ensure {{ role_name }} config directory ownership
  ansible.builtin.file:
    path: "{{ configdirs[role_name] }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true

- name: Create {{ role_name }} config
  ansible.builtin.template:
    src: "{{ role_name }}.hcl.j2"
    dest: "{{ configdirs[role_name] }}/{{ role_name }}.hcl"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: Restart {{ role_name }}
  ansible.builtin.systemd:
    name: nomad
    state: restarted
