---
- name: Create Telegraf config directory
  ansible.builtin.file:
    path: /etc/telegraf
    state: directory

- name: Create Telegraf config
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  register: telegraf_config

- name: Create Telegraf systemd service
  ansible.builtin.template:
    src: telegraf.service.j2
    dest: /etc/systemd/system/telegraf.service
  register: telegraf_service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: telegraf_service.changed

- name: Check Telegraf service status
  ansible.builtin.systemd:
    name: telegraf
  register: telegraf_status

- name: Start Telegraf service if not running
  ansible.builtin.systemd:
    name: telegraf
    state: started
  when: telegraf_status.status.ActiveState != 'active'

- name: Restart Telegraf service if configuration or service changed
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
  when: telegraf_config.changed or telegraf_service.changed

- name: Enable Telegraf service
  ansible.builtin.systemd:
    name: telegraf
    enabled: true
