---
- name: Generate Consul gossip key
  ansible.builtin.command: consul keygen
  register: consul_gossip_key_output
  run_once: true

- name: Set Consul gossip key fact on all hosts
  ansible.builtin.set_fact:
    consul_gossip_key: "{{ consul_gossip_key_output.stdout }}"

- name: Save Consul values to .secrets.yml
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/.secrets.yml"
    regexp: '^{{ item.name }}:'
    line: "{{ item.name }}: {{ item.value }}"
    create: true
  delegate_to: localhost
  become: false
  run_once: true
  loop:
    - { name: consul_gossip_key, value: "{{ consul_gossip_key }}" }
