---
bindir: /usr/bin
configdir: /opt/homelab/config
configdirs:
  - consul-server: "/opt/homelab/config/consul-server.d"
  - nomad-server: "/opt/homelab/config/nomad-server.d"
  - consul-agent: "/opt/homelab/config/consul-agent.d"
  - nomad-agent: "/opt/homelab/config/nomad-agent.d"
  - consul-agent-root: "/opt/homelab/config/consul-agent-root.d"
  - nomad-agent-root: "/opt/homelab/config/nomad-agent-root.d"
datadir: /opt/homelab/data
datadirs:
  - consul-server: "/opt/homelab/data/consul-server"
  - nomad-server: "/opt/homelab/data/nomad-server"
  - consul-agent: "/opt/homelab/data/consul-agent"
  - nomad-agent: "/opt/homelab/data/nomad-agent"
  - consul-agent-root: "/opt/homelab/data/consul-agent-root"
  - nomad-agent-root: "/opt/homelab/data/nomad-agent-root"
user: hashi
group: hashi
uid: 2000
gid: 2000
#gid: 100

tld: net.
domain: shamsway
datacenter: shamsway
admin_user: matt

dns1: 192.168.252.6
dns2: 192.168.252.7

internal_subnets:
  - 192.168.252.0/24
  - 192.168.240.0/24

user_public_key: /Users/melliott/.ssh/id_rsa.pub
#ansible_ssh_pipelining: false

restic_repository: "s3:s3.us-west-000.backblazeb2.com/octant-backup"

consul:
  # Check this blog post before enable this variable
  # https://www.hashicorp.com/blog/protecting-consul-from-rce-risk-in-specific-configurations
  enable_script_check: false
  ca_enabled: true
  cname: consul.shamsway.net
  # Services #
  # agent_services: false
  # service_sanity_healthcheck: true # Perform healthcheck on services priot to registration
  ports:
    http: 8500
    https: 8501
    dns: 8600
    grpc: 8502
  port_list:
    - 8500/tcp
    - 8600/tcp
    - 8502/tcp

podman: true
docker: false

nomad:
  ports:
    http: 4646
    rpc: 4647
    gossip: 4648
  port_list:
    - 4646/tcp
    - 4647/tcp
    - 4648/tcp
    - 4648/udp
